[package]
name = "music-vibes"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
buttplug = "5.1.5"
rodio = "0.14.0"
flume = "0.10.9"
clap = { version = "3.0.0", features = ["derive"] }
audio-capture = { path = "../audio-capture" }
parking_lot = "0.11.2"
